apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-configmap
  name: nginx-configmap
spec:
  containers:
    - image: nginx
      name: nginx-configmap
      resources: {}
      volumeMounts:
        - name: myvol
          mountPath: /also/a/path
  volumes:
    - name: myvol
      configMap:
        name: another-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
